# Site settings
title: Coldmooon's Blog
header-img: img/home-bg.jpg
email: xxx@xxx.com
description: ""
baseurl: ""
url: "http://coldmooon.github.io"
# twitter_username: SBootstrap
github_username:  coldmooon
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
